[package]
name = "libunrealpak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.2"
base64 = "0.21.0"
byteorder = "1.4.3"
sha1 = "0.10.5"
thiserror = "1.0.38"
